* What Is Wget?
GNU Wget is a computer program that retrieves content from web servers.
Wget is a command-line file downloader that can handle just about any file downloading task normal and power users will ever need to do.
It has versions available for Windows, Mac, and Linux. If it is not already installed on your machine, install it now.

* Wget Command-Fu
This guide is to save other sorry plebs from needing to RTFM in figuring out how to use wget for various purpose including from 4chan and other imageboards (And also useful for me since I'll forget how to use it in a few months anyway and just copy paste...).
There are lots of specific website scraper and image downloaders in existence, but they eventually become outdated and broken.
In the long run =wget= will remain as the superior, powerful and general purpose tool as long as the world wide web exist. Hence, you will save time following this guide instead.

** Basic syntax
=wget [options] [url]=

*** Useful Options for Image Scraping
There are tons more, but these are the most useful ones.

+ `-r` downloads files recursively, downloading links that are contained in already downloaded documents. This is essential because a common case is one url that contains all image file links.
+ `-l [n]` controls the maximum recursion level. `n` will practically always be one for image scraping.
+ `-H` allows downloads from different hosts than the original url. This is useful because many sites show images hosted at different domains.
+ `-D [domains]` tells what additional hosts to download from. You will probably have to 'View Source' in your browser to know for sure what to put here. `domains` is a comma separated list of domain names.
+ `-P [prefix directory]` tells where to save the downloaded files. The default is the current directory.
+ `-nd` avoids creating additional hierarchy.
+ `-A [extensions]` tells what file extensions to save.
+ `-E` adjust-extension. Some html file does not end in /.html/ for some reason so this flag will detect html file and set the extension automatically.
+ `-m` mirror the target url. 

** 4chan

*** How to Download whole thread from 4chan and convert the link:
#+BEGIN_SRC sh
  wget -E -nd -r -l 1 -H -N -nc -np -e robots=off -k <thread url>
#+END_SRC

*** Download images from 4chan:

#+BEGIN_SRC sh
  wget -P images -nd -r -l 1 -H -D i.4cdn.org -A png,gif,jpg,jpeg,webm <thread-url>
#+END_SRC

*** Download images from 8chan:

#+BEGIN_SRC sh
  wget -P images -nd -r -l 1 -H -D media.8ch.net -A png,gif,jpg,jpeg,webm <thread-url>
#+END_SRC


* Resources
+ https://gist.github.com/tayfie/6dad43f1a452440fba7ea1c06d1b603a
+ https://the-eye.eu/public/Wget_Linux_Guide.pdf
